# Generated by Django 4.1.1 on 2022-11-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_pic',
            field=models.ImageField(default='', upload_to='media/displaypic'),
        ),
    ]
