# Generated by Django 4.1.1 on 2022-11-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
